### ISSUE TITLE
Deep Mod Learning Book Uncraftable, we think its an issue wit Guide-API

### ISSUE THREAD

**Issue by TacticalUniverse** [xt9/DeepMobLearning#11]
https://github.com/TacticalUniverse/Beyond-The-Void-2/issues/24

**Comment by xt9** [comment]
Not a DML issue. Closed.

**Comment by xt9** [comment]
@Ipsis Thanks for the heads up, I'll take a look at it. When I originally wrote the manual I did peek at your repo, so this is a little bit of human error on my part.

I'll make sure to change it to something more unqie.

**Comment by Ipsis** [comment]
@xt9 I based my Guide-API book on the BloodMagic one, so I caused the first duplicate when I registered it in the same way as theirs. I was just really lucky that they changed theirs to be unique before anyone noticed :)
