### ISSUE TITLE
Licensing Clarification

### ISSUE THREAD

**Issue by nate2014jatc** [xt9/DeepMobLearning#12]
Hi there!
We'd love to use your mod(s) in our pack, but we can't find any info about the licensing of DeepModLearning.
The CurseForge page says that it's "all rights reserved," but we would appreciate additional clarification.

**Comment by xt9** [comment]
You can add/use it in any pack.

**Comment by CrankySupertoon** [comment]
@xt9 How about Modpacks on the FTBApp. Do you give permission their.

**Comment by xt9** [comment]
Sod off Cranky, if the FTB team wants permission they will ask me themselves.

**Comment by CrankySupertoon** [comment]
@xt9 Im asking if you give permission for DeepMobLearning to be included in my modpack hosted on the FTBApp.

**Comment by xt9** [comment]
You may @CrankySupertoon

**Comment by CrankySupertoon** [comment]
@xt9 Dose that also mean you consent for FTB to redistribute you mod so it can be included in the FTBApp?

**Comment by xt9** [comment]
They have received permission, yes.
