### ISSUE TITLE
Crescent Hammer Resets Digital Mob Agonizer

### ISSUE THREAD

**Issue by Vyraal1** [xt9/DeepMobLearning#19]
Pack: FTB Interactions v 1.0.1
DML: 2.4.2
DML Blood Addon - 1.0.0

Right clicking a digital mob agonizer with a crescent hammer resets the block entirely, deleting any energy, memory or linked altar, and data models inside it.

**Comment by maniacpsycho** [comment]
not just the agoniser, the sim chamber voids its inventory on rotate too

**Comment by xt9** [comment]
Fixed in 8c75a19, Thanks for reporting o/
