### ISSUE TITLE
[Feature request] Custom Data Models

### ISSUE THREAD

**Issue by LordEpos** [xt9/DeepMobLearning#20]
This is a pretty big feature request, and I don't know enough about coding to be able to say for sure how doable it is, but I think a good amount of the groundwork is already there in the configs. 

I wanna be able to, as a modpack maker, define custom data models.

Using Crafttweaker & the configs, outputs from said data models are already pretty easy to set, and specifying the needed mobs can also be done from existing configs. All I'd need is a function in the config files to add an additional data model type, give it a picture, specify what kind of matter it makes upon failure, and then fill in the existing configs for said model. Ideally also custom matter options. (IE aether matter)

Using [Resource Loader](https://minecraft.curseforge.com/projects/resource-loader) it should be possible for a user to add a custom image into the game, but so as to prevent it from being a hard dependency, packaging in a picture for a default data model image that's simply a "?" symbol should more than suffice.

This would allow the users who are asking for Aether and Cyberware integrations in this issues pile (both of which I'd like to have in my own modpack) to simply fix the issues for themselves, and potentially even allow for such mobs to be integrated very easily on the dev end and be packaged in with the mod.

**Comment by HellishINC** [comment]
This would definitely be the better route than implementing every requested mod under the sun. Personally I'd like support for Grimoire of Gaia but that would most likely take much time away from actual mod development as it has something like 50 creatures.

**Comment by xt9** [comment]
Hellish if you want to partake in this issue I suggest you clean up your profile, it's disrespective to the platform we're currently on and I won't stand for it

**Comment by xGarionx** [comment]
First of all great mod!
And besides that i second that, as a pack author that searches for stability in every way possible and like to built upton content mod authors provide this would be really usefull. 
Maybe a connection to content tweaker for additional matter or data models (ressource loader seems a really good addition aswell) could handle that.
Thank for this wonderfull mod :)

**Comment by AnthonyFuller** [comment]
Any update on Craft Tweaker and Resource Loader compatibility?

**Comment by LordEpos** [comment]
I suspect there's a reason that this has been the way that it is up until now, and this request is a much bigger ask than it sounds like. Xt9 hasn't marked it as something he is not working on, though, so I'd assume it's still on the way.

**Comment by andrelec1** [comment]
Any news ?

It will be awsome if we can add remove/add new data model  by  Creaftweaker .

**Comment by xt9** [comment]
1.12 Will recieve no further features/integrations

**Comment by LordEpos** [comment]
Well dang, I waited over a year for this feature before finishing my modpack, only to learn it's not happening. I really love this mod and its presentation, but being strung along that long for nothing leaves a pretty bad taste in my mouth. At this point it will take some fair amount of effort to untangle deep mob learning from my modpack or code an addon myself, and it's late in the life-cycle of 1.12 to find someone else to. Not impressed with how this was handled.

**Comment by xt9** [comment]
You were never strung along, I don't think I ever indicated an intent to add this feature to 1.12.
Your comment is a wierd take, just because you make an FR it doesn't mean it will magically happen.
