### ISSUE TITLE
[bug] Ender Dragon multiple kill credit from one kill.

### ISSUE THREAD

**Issue by iambadatusername** [xt9/DeepMobLearning#21]
pack- FTb Sky Odyssey

When you kill ender dragon while levelling up drogon data module. When dragon is dead particels of dead dragon fly to bedrock platform in the middle. When it is dead and you shoot it (i used archangels smite fron project e) it counts as a kill.

 (Sorry for poor explaniation i hope you understood)

**Comment by xt9** [comment]
Fixed in befee76
