### ISSUE TITLE
[bug] Connecting a hopper to the Trial Keystone crashes the game.

### ISSUE THREAD

**Issue by hansf123** [xt9/DeepMobLearning#22]
I put a hopper above the trial keystone block, to try to automate putting in keys. When keys are inserted into the hopper, the game crashes immediately. Upon reloading the game and attempting to enter the world, the game crashes during loading of the world. World was able to be recovered by removing the trial keystone block through MCedit, and is now loadable.

Bug is reproducible with current settings.
Modpack: FTB Sky Odyssey

**Comment by xt9** [comment]
I would need a crash log to be able to errorshoot this.

**Comment by DBArcAngel** [comment]
[crash-2019-04-24_20.11.48-server.txt](https://github.com/xt9/DeepMobLearning/files/3113848/crash-2019-04-24_20.11.48-server.txt)
I did the same as OP using the same pack, the log doesn't mention this mod but it does mention foamfix ,rwtema and hoppers. The crash/hang happened right after I placed a trial key in a hopper connected to the trial keystone.

**Comment by xt9** [comment]
Fixed in 8c75a19, Thanks for reporting o/
