### ISSUE TITLE
Errors on Game loading

### ISSUE THREAD

**Issue by AssB0ys** [xt9/DeepMobLearning#23]
On game loading I get the following errors:
https://pastebin.com/59zeFpgd
Seems to be related to the recipes from the mods that are not even present in my game.
full log at:
https://pastebin.com/QKF4Tr6G
mods intslled are just deepmoblearning(deepmoblearning-1.12.2-2.5.0-universal.jar) and the JEI(jei_1.12.2-4.15.0.275).
Forge version is 14.23.5.2835
game version is 1.12.2

edit: I removed the not default game IDs from the config and the errors still presist

**Comment by xt9** [comment]
Not fatal errors or bugs. I think I already cleaned up the loading conditions for recipes in 1.13 so this should already be resolved.

**Comment by AssB0ys** [comment]
Good. I am cautious for every error in the log because crash or possibly world corruption doesn't always happen at the game load or the world load. Thanks for making this clear.
