### ISSUE TITLE
[Bug] Crash during Trial

### ISSUE THREAD

**Issue by SaraTri** [xt9/DeepMobLearning#24]
Server crashed during trial when two players were doing the trial after the other one left the area.

Modpack: SkyFactory 4 (4.0.2)
Mod Version: 14.23.5.2831
Forge Version: 2.5.0
Crash Log: https://pastebin.com/b9ETrRp9

**Comment by xt9** [comment]
Thank you for the report, will look into it

**Comment by xt9** [comment]
Fixed in 8c75a192da367ef2246062d885269eb8243d1571, Thanks for reporting o/
