### ISSUE TITLE
[Bug] Mob kills not counted toward anything

### ISSUE THREAD

**Issue by AlchemicPhoenix** [xt9/DeepMobLearning#25]
So, I've been playing the FTB Sky Odyssey modpack and decided to try this mod. I had recently watched a few youtubers use it in their lets plays of the same pack. They had no issues, however, i did. I had made a wither skeleton data module to make a passive wither skeleton farm for their heads but when i killed the wither skeletons manually nothing happened. The kills were not counted. I thought it was because the skeletons were spawned using cursed earth in the nether, but after having killed naturally spawned ones with the same results, i determined that that was not the case. I then tried to attune a trial key to any other mob and nothing happened, the key was not attuned. If this issue is only happening to me i would simply like to know how i might be able to go about fixing it. Trying to use the mod does not crash my game or anything severe like that. This seems like a very fun and interesting mod, i just want to be able to use it.

**Comment by xt9** [comment]
What config value do you have for S:witherskeleton under the "data model mob names" section of the config? Also what are you using to kill them?

**Comment by AlchemicPhoenix** [comment]
It says:
"# Wither Skeleton
    S:witherskeleton <
        minecraft:wither_skeleton
">"
(note i added the quotations in for posting it here so that it didnt change formatting stuff when i posted it.)
All the configs are the default ones from when i downloaded the pack. As for what im using to kill any mob, it's either the emeradic AIOT from Actually Additions or a vanilla diamond sword. I thought it was the weapon too so i tried the diamond sword. I also thought it could be the armor i was wearing which was the gem armor from ProjectE, so i tried wearing vanilla diamond armor too. No change in results. Also its not just a problem with wither skeletons, it's any mob that can be used in the mod.

**Comment by xt9** [comment]
Do you have the models in the Deep Learner? Data Models won't acquire data from kills unless they are in one.

**Comment by AlchemicPhoenix** [comment]
........... I didnt see anyone else use one in videos so i didnt know about it. But that did fix it. Sorry to bother you. You might want to consider implementing a guide book into the mod for idiots like me. Thanks for the help.

**Comment by xt9** [comment]
There is a guidebook :octocat: But glad we could figure it out
