### ISSUE TITLE
Config options not taking place for item drops!

### ISSUE THREAD

**Issue by xaleb** [xt9/DeepMobLearning#26]
What title says. I have the config file set to include items in the loot fabricator from mods into the vanilla mobs. In the correct format.

**Comment by xt9** [comment]
Thanks for the issue report, In order to properly reproduce this I would need your config file, and some more information about Forge/DeepMobLearning version and what the current/expected behaviour of this is, "not taking place" is a bit thin and I don't quite understand what your issue is.

**Comment by xaleb** [comment]
Here is my portion of the config file in question with edits made that aren't taking place in game, I am using the most recent forge for 1.12.2 as well as the most recent version of deepmoblearning.

Config is as follows:

"pristine output items" {
    # Blaze
    S:blaze <
        minecraft:blaze_rod,22,0
        thermalfoundation:material,32,771
        xreliquary:mob_ingredient,1,7
     >

    # Creeper
    S:creeper <
        minecraft:gunpowder,64,0
        minecraft:skull,6,4
        xreliquary:mob_ingredient,1,3
     >

    # Dragon
    S:dragon <
        minecraft:dragon_breath,32,0
        minecraft:dragon_egg,1,0
        draconicevolution:dragon_heart,1,0
        draconicevolution:draconium_dust,64,0
     >

    # Enderman
    S:enderman <
        minecraft:ender_pearl,6,0
        minecraft:end_crystal,1,0
        enderio:block_enderman_skull,2,0
        xreliquary:mob_ingredient,1,11
     >

    # Ghast
    S:ghast <
        minecraft:ghast_tear,8,0
     >

    # Guardian
    S:guardian <
        minecraft:prismarine_shard,32,0
        minecraft:prismarine_crystals,32,0
        minecraft:fish,64,0
        xreliquary:mob_ingredient,1,16
        minecraft:sponge,1,0
     >

    # Shulker
    S:shulker <
        minecraft:shulker_shell,18,0
        minecraft:diamond,2,0
        darkutils:shulker_pearl,4,0
     >

    # Skeleton
    S:skeleton <
        minecraft:bone,64,0
        minecraft:arrow,64,0
        minecraft:skull,6,0
        xreliquary:mob_ingredient,1,0
     >

    # Slime
    S:slime <
        minecraft:slime_ball,32,0
        xreliquary:mob_ingredient,1,4
     >

    # Spider
    S:spider <
        minecraft:spider_eye,16,0
        minecraft:string,64,0
        minecraft:web,8,0
        xreliquary:mob_ingredient,1,2
     >

    # Thermal Elemental
    S:thermalelemental <
        thermalfoundation:material,16,772
        thermalfoundation:material,16,770
        minecraft:snowball,16,0
        thermalfoundation:material,8,2050
        thermalfoundation:material,8,2052
        thermalfoundation:material,8,2048
     >

    # Tinker construct slime
    S:tinkerslime <
        tconstruct:edible,18,1
        tconstruct:edible,18,2
        tconstruct:edible,18,4
        tconstruct:slime_sapling,4,0
        tconstruct:slime_sapling,4,1
        tconstruct:slime_sapling,4,2
     >

    # Twilight Darkwood creatures
    S:twilightdarkwood <
        twilightforest:armor_shard_cluster,5,0
        twilightforest:carminite,16,0
        minecraft:diamond_ore,3,0
        minecraft:emerald_ore,2,0
        minecraft:fish,32,0
     >

    # Twilight Forest(Biome, not the whole mod)
    S:twilightforest <
        twilightforest:naga_scale,16,0
        twilightforest:charm_of_life_1,2,0
        twilightforest:charm_of_keeping_1,2,0
        minecraft:paper,64,0
        minecraft:book,32,0
     >

    # Twilight Glacier creatures
    S:twilightglacier <
        twilightforest:arctic_fur,16,0
        twilightforest:alpha_fur,8,0
        minecraft:packed_ice,16,0
        minecraft:feather,32,0
        twilightforest:charm_of_life_2,1,0
        twilightforest:charm_of_keeping_2,1,0
     >

    # Twilight Swamp creatures
    S:twilightswamp <
        twilightforest:steeleaf_ingot,16,0
        twilightforest:ironwood_raw,8,0
        twilightforest:fiery_ingot,5,0
        twilightforest:hydra_chop,16,0
        minecraft:gold_ingot,22,0
        minecraft:red_mushroom,32,0
        minecraft:slime_ball,16,0
     >

    # Witch
    S:witch <
        minecraft:redstone,32,0
        minecraft:glowstone_dust,32,0
        minecraft:sugar,64,0
     >

    # Wither
    S:wither <
        minecraft:nether_star,3,0
     >

    # Wither Skeleton
    S:witherskeleton <
        minecraft:skull,18,1
        minecraft:coal,64,0
        xreliquary:mob_ingredient,1,1
        extrautils2:ingredients,1,10
        darkutils:material,16,0
        nex:wither_bone,16,0
        iceandfire:witherbone,16,0
        tconstruct:materials,16,17
     >

    # Zombie
    S:zombie <
        minecraft:rotten_flesh,64,0
        minecraft:iron_ingot,16,0
        minecraft:carrot,32,0
        minecraft:potato,32,0
        xreliquary:mob_ingredient,1,6
     >
}

**Comment by katubug** [comment]
I'm using deepmoblearning-1.12.2-2.5.1-universal and forge-1.12.2-14.23.5.2825-universal and my config seems to be working fine. Here's a pastebin of the whole file, if it helps:
https://pastebin.com/UnV7d0Ki

As an example, I put the Pristine Zombie Matter into the powered Loot Fabricator and it gives me the option to produce Rotten Flesh, Iron Ingots, Carrots, Potatoes, Zombie Hearts, and Zombie Brains.

**Comment by Syrchalis** [comment]
The game does not pull the info for the loot conversion from the server's config but from the client. So if you changed the config on the server it will work correctly, but only show when you put the essence into the loot fabricator and activate the process of making the loot.
