### ISSUE TITLE
[Feature Request] Pink Slime Data Module

### ISSUE THREAD

**Issue by CookedPages** [xt9/DeepMobLearning#27]
Pink slime is a pain to farm, and I have had many instances of needing to create and kill many, many of them to get all the pink slime balls needed in a pack. Being able to kill 3-6? and then let DML farm the rest would be fantastic. (pairs nicely with the pink slime seeds in SF4 atm too)

**Comment by LordEpos** [comment]
Most mod data models are probably coming with the custom data models before. If I was the dev, I wouldn't want to spend extra work on a feature that's mostly obsolete. Once that's available, I'd be happy to make a Curseforgable config file featuring this mob, and any others recommended here. (In fact, every mob suggested here thusfar has been one that's in my own modpack, so I'll kinda have to.)

**Comment by lesdmark** [comment]
I would also like to request the pink slime module.

**Comment by niklas2233** [comment]
I would also like to see this getting added

**Comment by xt9** [comment]
1.12 Will recieve no further features/integrations
