### ISSUE TITLE
[Feature Request] Chaos Dragon Data Module

### ISSUE THREAD

**Issue by Damien-Reave** [xt9/DeepMobLearning#29]
I think it would be pretty great to have the ability to farm Chaos Shards like this. But it would need a huge power cost, which would probably entail increasing the 6666 rf/t limit.

**Comment by AnthonyFuller** [comment]
Yes. Possibly a upgraded version of the machine is needed.

**Comment by xt9** [comment]
1.12 Will recieve no further features/integrations
