### ISSUE TITLE
[Feature Request] Configuration Options relating to the Armor Set

### ISSUE THREAD

**Issue by katubug** [xt9/DeepMobLearning#30]
Hi there! Firstly, thank you for the great mod! Secondly, would it be possible to add a config option to disable the flight bonus on the armor set, or balance it somehow?  I'm trying to limit creative-style flight in my world.

**Comment by xt9** [comment]
Thanks! Yeah that sounds like a reasonable request, I'll make sure it's part of the next mod update.

**Comment by katubug** [comment]
Thank you so much!

**Comment by xt9** [comment]
Sorry for the delay. This is added in 2.5.2

**Comment by katubug** [comment]
Thanks so much!
