### ISSUE TITLE
mod config - pristine output item not showing up pneumaticcraft:plastic:1

### ISSUE THREAD

**Issue by wideblaze** [xt9/DeepMobLearning#31]
unable to get pristine output item for pneumaticcraft:plastic:1 (red plastic) or any other color.

may be due to extra ":" in the identifier used by pneumaticcraft to specify color

`
"pristine output items" {
    # Blaze
    S:blaze <
        minecraft:lava_bucket,1,0
        minecraft:fireworks,10,0
        minecraft:glowstone,1,0
        minecraft:magma,1,0
        minecraft:magma_cream,1,0
        minecraft:netherrack,16,0
        minecraft:quartz_ore,4,0
        minecraft:blaze_rod,2,0
        pneumaticcraft:plastic:1,1,0
        pneumaticcraft:plastic:11,1,0
        pneumaticcraft:plastic:12,1,0
        pneumaticcraft:plastic:13,1,0
        pneumaticcraft:plastic:14,1,0
     >
`

Other pneumaticcraft items work:         pneumaticcraft:ingot_iron_compressed,1,0

config file:  https://github.com/wideblaze/DigSite/blob/master/config/deepmoblearning.cfg

**Comment by xt9** [comment]
Please read the config documentation. Meta is not separated by `:`
Good luck.

```
##########################################################################################################
# pristine output items
#--------------------------------------------------------------------------------------------------------#
# Entries for Loot fabricator outputs from the different pristine items.
# Input format "minecraft:coal,64,0"
# Where minecraft:coal is the registryName, 64 is the amount and 0 is the damagevalue/meta. "," is the delimiter.
# Optionally supports NBT tags, example:
# deepmoblearning:glitch_infused_sword,1,0,{display:{Name:"Not a sword really"}}
##########################################################################################################
```

**Comment by wideblaze** [comment]
yep -- that was my problem -- thought that was just for damage
thanks
