### ISSUE TITLE
[Suggestion]Enderman Trial without thunderdome

### ISSUE THREAD

**Issue by awqsrem** [xt9/DeepMobLearning#33]
As the title suggests, the enderman trial is very annoying(and easy) with the Thunderdome "bonus".

The endermen just teleport around until they die... which can take quite a while and if you leave, you lose the key.

What I'm suggesting is, that each enderman trial would have this disabled and maybe always set the weather to clear, so the endermen don't teleport around.

Also maybe tether them to the arena so they teleport back into the arena every couple of seconds to make it less annoying.

**Comment by xt9** [comment]
The endermen is not supposed to teleport during the trial , and the only pack where I've seen this behaviour is in sf4. 

I intend to change how I disable their teleporting so it works across the board. I'll close this issue once I've changed it as it would be killing 2 birds with one stone.
