### ISSUE TITLE
[Suggestion] Config to disable weather change from trials

### ISSUE THREAD

**Issue by al132mc** [xt9/DeepMobLearning#34]
In my modpack, the doWeatherCycle is disabled, so whenever someone activates a trial the world is permanently in a state of storms until someone intervenes with the privileges to clear weather with the weather command. Ideally, there would be a config where we could prevent the weather change from happening at all.

**Comment by Gurkenpete** [comment]
Yes, I second this, as this is something bugging me as well. A possible solution would be, if you could insert an unattuned key to stop all effects of the trial, also restoring the weather to what it was before.

**Comment by xt9** [comment]
Fixed in febe2e8
