### ISSUE TITLE
[bug] Crashing when using trial

### ISSUE THREAD

**Issue by Amvermain** [xt9/DeepMobLearning#35]
I tried Enderman Trial.
when I put trial key to keystone, and activated it. first wave was successful.
But then server just gone.

i think i attached crash log here, but when you can't see it, please notice me that I haven't uploaded log.

**Comment by Amvermain** [comment]
https://pastebin.com/kgeJV3s9

here is pastebin link.

**Comment by xt9** [comment]
Please update to the latest version, this should be fixed.
