### ISSUE TITLE
[Suggestion} config for removing matter crafting recipes, increased max power usage

### ISSUE THREAD

**Issue by Genesiz13** [xt9/DeepMobLearning#36]
A few config suggestions:

1. ability to remove all crafting recipes using the XP matters( overworldian, hellish, etc)
2. increased max power usage for the simulators above 6666 rf/t
3.  ability to change the drop rate of XP matters.
4. ability to change pristine matter drop rates for individual models 

great mod, keep it up ( my computer thanks you for the decreased load)

**Comment by xt9** [comment]
1.12 Will recieve no further features/integrations
