### ISSUE TITLE
Game Crash on Wave 5 of Self-Aware Skeleton Trial (SkyFactory 4)

### ISSUE THREAD

**Issue by dragonkid828** [xt9/DeepMobLearning#37]
Happened twice, my friend started the Self-Aware Skeleton Trial, and shortly after Wave 5 was announced, nothing spawned and the server crashed. At the time I was just placing down a laser base + drills, and i don't think it had anything to do with that. We tested it a 2nd time to make absolutely sure it was the trials.
Two logs: 
https://pastebin.com/zW7JgqPp
https://pastebin.com/x3DPEMzx

(Might be redundant and be almost the same but, just in case)

**Comment by xt9** [comment]
This issue is fixed on the latest version.
