### ISSUE TITLE
[suggestion] Polymer clay consumed when pristine procurement is rolled

### ISSUE THREAD

**Issue by Andr0oS** [xt9/DeepMobLearning#40]
Taking a data model out of a machine is fairly wasteful if you don't disable it because it eats a polymer clay every time it begins a new iteration. Since it begins a new process immediately after finishing the last, it will eat clay if you take out a model after it finished an iteration. This could be fixed by simply changing the timing of when clay is used to be part of the roll for pristine matter, since that's when it really counts.

**Comment by xt9** [comment]
1.12 Will recieve no further features/integrations
