### ISSUE TITLE
Recipe parsing error

### ISSUE THREAD

**Issue by KokSaker** [xt9/DeepMobLearning#41]
Hello. I have some odd error output in the log https://pastebin.com/rEUtkMfF I briefly went through it and saw that this mod requires Twilight Forest mod as a dependency, which is not stated at the curseforge download page. I don't have the Twilight Forest and possibly Tinkers' Constructs too and I didn't plan to add them to my personal pack. Although I am not sure about this, the log mentions the tinkers slimes too.

**Comment by xt9** [comment]
You can safely ignore those errors, they are thrown because I haven't added a dependency field to the recipes for TF stuff, so they're loaded even though the mod might not be in a pack. They're not fatal errors and they wont affect your ingame experience.

**Comment by KokSaker** [comment]
Is adding a dependency field to the recipes for TF stuff very hard to do? If it's tedious work, maybe I could help? I am not really familiar with Java, but if you point me to the right direction I could probably assemble some data for you, make lists of items that have to be added to the dependencies lists.
