### ISSUE TITLE
Passive Mobs - For Server's Sake Please!

### ISSUE THREAD

**Issue by Coxworth** [xt9/DeepMobLearning#42]
I see passive mobs were already ruled out because they don't really fight back, but you can run this entire mod without really fighting much by just simulating instead anyway... 

...and this is FAR FAR better on the server than running mob farms. I now have users running simulators (yay!) for the hostile mobs and then huge pig/cow/chicken farms which are ticking too hard.

**Comment by Coxworth** [comment]
Maybe just make it something that can be optionally turned off in config?

**Comment by johnch18** [comment]
Seconding this. Forced exploration is an annoying mechanic

**Comment by YaibaToKen** [comment]
Perhaps have it be off by default, as to avoid a sudden change in behavior for existing worlds. Make it have smaller returns if need be, to compensate the lack of risk in killing these mobs for the Data Model set up.

**Comment by xt9** [comment]
1.12 Will recieve no further features/integrations
