### ISSUE TITLE
[Suggestion / Discussion] XP automation

### ISSUE THREAD

**Issue by rlf23240** [xt9/DeepMobLearning#48]
Sorry if I didn't notice, is there any way to auto convert living matter to liquid XP? Or at least turn into XP orb and collect by machine of other mod?
Also, thank you for such great mod!

**Comment by xt9** [comment]
1.12 Will recieve no further features/integrations
Also I know there is an EnderIO integration for this, just pipe the solid matter into one of their tanks.
