### ISSUE TITLE
[Suggestion] More locations

### ISSUE THREAD

**Issue by xaein** [xt9/DeepMobLearning#5]
Would be nice to have bottom left/right as well as the top left/right that we have now, as i have other information addons set up for top left and right atm

**Comment by xt9** [comment]
Sounds like that could be useful, I'll add it as soon as possible.

**Comment by xt9** [comment]
Thanks for the suggestion, this is now a thing. 
**Fixed in https://github.com/xt9/DeepMobLearning/commit/5fba7cac044820442bdfb945d2764e3021854330**
