### ISSUE TITLE
[.lang] wrong text displayed in the book for "System Malfunction" chapter

### ISSUE THREAD

**Issue by macks2008** [xt9/DeepMobLearning#54]
I'm not sure where exactly the problem lies (my suspicions indicate it's probably in a lang file or the like), but when I view the "System Malfunction" chapter in the guidebook, I get the text for the Trials chapter on the left side instead (sub entries still display and work correctly though). This happened in v 2.5.2. A client debug log is attached. If you need any further information, I'd be happy to oblige!
[debug.log](https://github.com/xt9/DeepMobLearning/files/3638963/debug.log)

**Comment by xt9** [comment]
Fixed in d6325227d6a5f49568637b1e65b50e17038c82d7
