### ISSUE TITLE
[unexpected behavior]transparent blocks don't count as full blocks for trials

### ISSUE THREAD

**Issue by macks2008** [xt9/DeepMobLearning#56]
When setting up for my first ever trial, I happened to notice that blocks like glass (presumably due to transparency) don't count as valid platforms for the Trial Keystone's arena... Is this intentional? Because if so, at the very least, you should probably change the keystone's GUI text (which currently calls for "full blocks") to clarify; if it's not, obviously you have a bit of debugging to do! In either case, here's a log, just in case you need more information.
[debug.log](https://github.com/xt9/DeepMobLearning/files/3645321/debug.log)

**Comment by xt9** [comment]
I think this is fine as it is, the average user should understand this
