### ISSUE TITLE
Disable Looters in Trials/Configs for them 

### ISSUE THREAD

**Issue by Conansson** [xt9/DeepMobLearning#58]
Hello, 
i am creating a Modpack and want to use this mod in the midgame to create nether drops from creatures. But sometimes, Looters are spawning and dropping Diamond Ore, destroying my progression of having diamonds only later on. I didn't find a config for disabling them/ certain outputs from them. 
Can you add a config option for this? 
Love your mod!

**Comment by xt9** [comment]
Their loot is set in the loot_hoarder loot table. 
https://github.com/xt9/DeepMobLearning/blob/1.12/src/main/resources/assets/deepmoblearning/loot_tables/loot_hoarder.json

You could alter that with something like https://github.com/Daomephsta/LootTweaker
