### ISSUE TITLE
[Enhancement] Mob support for mods

### ISSUE THREAD

**Issue by YaibaToKen** [xt9/DeepMobLearning#6]
Any chance we could get mob support? I'm wondering if we could generate data models from a base template and the mob's face. The loot should be retrievable from the mob's loot table.

Not sure if we can tell whether it's overworldian or not but that's honestly the least of the issues.

**Comment by YaibaToKen** [comment]
How hard is it to render the entity for which the data model is being generated? While I'm used to programming, I'm quite new to Forge and Minecraft's code. Seeing as we'd already be  looking up all registered entities and creating data models for them, we'd already have an entity to render, although we'd be missing the trivia info itself.

**Comment by xt9** [comment]
All of the metadata/params for a given data model are constructed from https://github.com/xt9/DeepMobLearning/blob/master/src/main/java/xt9/deepmoblearning/common/mobs/MobMetaData.java

The actual implementations of each metadata is rather small https://github.com/xt9/DeepMobLearning/blob/master/src/main/java/xt9/deepmoblearning/common/mobs/TwilightDarkwoodMeta.java

But there is a number of things that are linked through the metadatas which makes it unsuitable for the end user and even an API.

If you have a request for a certain mod to be added you can open a new issue.
