### ISSUE TITLE
Peaceful

### ISSUE THREAD

**Issue by niklas2233** [xt9/DeepMobLearning#60]
Hey is there a way to make this work in peaceful? I tried making the config for basic start at 0 kills but it just made it to 1. It would be nice if you can add a config for it if that's possible. More variety is just nice to have so everyone can enjoy the most out of the mod.

**Comment by xt9** [comment]
In sf4 this was achieved by adding a crafting recipe for a model that was already at the Basic tier using nbt. Im not going to add a special case for this since it's rather easy to do in crafttweaker.
