### ISSUE TITLE
Simulation Chamber/Loot Fabricator ratio is not exact due to wasted ticks

### ISSUE THREAD

**Issue by RundownRhino** [xt9/DeepMobLearning#61]
Problem encountered in 1.12.2, but seems to be present in master too. 

At 0.3 chance for pristine at Self-Aware, 15s per simchamber and 2.5s per lootfab cycle, there is a natural simchamber to lootfab ratio of 20:1.
However, some players told me their loot fabricators were getting clogged with such a ratio.
After investigating, I noticed that starting to craft after a craft is finished takes a tick for DML machines. As their cycle durations are different, their wasted time percentage is also different: 1 tick out of 301 for simchamber and 1 out of 51 for lootfab. As such, the actual ration turns out to be ((301/0.3)/51)~=19.67 simchambers per lootfab.

I'm not sure if you will consider this a problem at all, but if you do, I'd suggest changing the code to, for example, do a single crafting tick on the same tick as starting a craft.

**Comment by xt9** [comment]
I'm sure you're correct but I don't consider it as a big issue. 
Thanks for taking the time to report it though. 🥂
