### ISSUE TITLE
Mixin 8

### ISSUE THREAD

**Issue by Firenzeo** [xt9/DeepMobLearning#65]
Please update the included mixins to version 8 if you are able to <3 
Many mods are getting around to this, and break any mods that haven't yet. 
I would hate to sacrifice my favorite server-friendly mob mod!

**Comment by xt9** [comment]
What are mixins and why would I want to update them/it?

**Comment by clienthax** [comment]
Highly likely refers to https://github.com/SpongePowered/Mixin
Theres issues with mods using mixin 6/7 being incompatible with the latest spongeforge due to the mixin changes.
However this mod isn't using mixins, so i have no idea why this issue exists.. 😕

**Comment by xt9** [comment]
Thanks @clienthax for the input, closing.
