### ISSUE TITLE
Suggestion to add Russian language

### ISSUE THREAD

**Issue by wibabe** [xt9/DeepMobLearning#72]
Hi, I translated Deep Mob Learding into Russian, I think maybe you need.
assets>deepmoblearning>lang
P.S Translation verified 100%
[Link to Pasterbin](https://pastebin.com/33DWwy8g)

**Comment by NotMyWing** [comment]
Not to be rude, but this translation is quite literal garbage lol. It's never a good idea to take an entire lang file and run it through an automated translation software.

**Comment by wibabe** [comment]
> Not to be rude, but this translation is quite literal garbage lol. It's never a good idea to take an entire lang file and run it through an automated translation software.

Okay now tell me what the program is? :)
