### ISSUE TITLE
Server Crashes

### ISSUE THREAD

**Issue by XNivekX** [xt9/DeepMobLearning#78]
Im running Deep Mob Learning 1.12.2-2.5.4.
The problem is that after the first successful trial (Glitches can spawn in the first trial), the second trial is crashing if a Glitch spawns
this is pretty weird since i'm already allocating 7GB of memory and it's still throwing a out of memory error.

https://pastebin.com/JFSsVMZZ this is the crash report

Hope to resolve the issue 
Thx in advance!

**Comment by xt9** [comment]
Thank you for the detailed issue. However it does not seem that DML is directly responsible for the crash.
Headcrumbs is running something in a new thread that it cannot allocate memory for. You could look for related issues in the [Headcrumbs repo ](https://github.com/ganymedes01/Headcrumbs/issues)

**Comment by XNivekX** [comment]
Okay I'll look into that thx anyways!
